import { createClient } from 'npm:@supabase/supabase-js@2';
type Media={file_id:string;file_name?:string;file_size?:number;mime_type?:string;thumbnail?:{file_id:string}};
type Msg={message_id:number;chat:{id:number;type:string;username?:string};from?:{id:number};sender_chat?:{id:number};text?:string;caption?:string;document?:Media;photo?:Media[];video?:Media;audio?:Media;voice?:Media;animation?:Media;reply_to_message?:{message_id:number}};
type Update={message?:Msg;edited_message?:Msg;channel_post?:Msg;edited_channel_post?:Msg};
const env=(name:string)=>{const value=Deno.env.get(name);if(!value)throw new Error('Missing '+name);return value};
const reply=(body:string,status=200)=>new Response(body,{status,headers:{'content-type':'text/plain; charset=utf-8'}});
Deno.serve(async req=>{if(req.method!=='POST')return reply('Méthode non autorisée',405);try{const secret=env('WEBHOOK_SECRET');if(req.headers.get('X-Telegram-Bot-Api-Secret-Token')!==secret)return reply('Accès refusé',403);const token=env('TELEGRAM_CHANNEL_TOKEN');const adminIds=env('ADMIN_IDS').split(',').map(s=>s.trim());const channel=env('TELEGRAM_CHANNEL_ID');const update=await req.json() as Update;const msg=update.channel_post||update.edited_channel_post||update.message||update.edited_message;if(!msg)return reply('Update ignorée');const isChannel=msg.chat.type==='channel'&&String(msg.chat.id)===channel;const isPrivate=msg.chat.type==='private'&&!!msg.from&&adminIds.includes(String(msg.from.id));if(!isChannel&&!isPrivate)return reply('Source non autorisée',403);
// Telegram omits the real author's user ID for anonymous channel posts; trust only the configured channel ID in that case.
if(isChannel&&msg.from&&!adminIds.includes(String(msg.from.id)))return reply('Auteur non autorisé',403);
const db=createClient(env('SUPABASE_URL'),env('SUPABASE_SERVICE_ROLE_KEY'),{auth:{persistSession:false}});
const send=async(text:string,chatId:number)=>{await fetch(`https://api.telegram.org/bot${token}/sendMessage`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({chat_id:chatId,text})})};
if(msg.text?.startsWith('/delete')){if(!isPrivate)return reply('Commande privée uniquement',403);const match=msg.text.match(/^\/delete(?:\s+(\d+))?/);const id=match?.[1]?Number(match[1]):msg.reply_to_message?.message_id;if(!id){await send('Utilisation : /delete IDENTIFIANT_DU_MESSAGE_DE_LA_CHAINE',msg.chat.id);return reply('Identifiant manquant')};const {data,error}=await db.from('posts').delete().eq('telegram_chat_id',Number(channel)).eq('telegram_message_id',id).select('file_url,thumbnail_url');if(error)throw error;const urls=(data||[]).flatMap(p=>[p.file_url,p.thumbnail_url]).filter(Boolean) as string[];const paths=urls.map(url=>{try{return decodeURIComponent(new URL(url).pathname.split('/storage/v1/object/public/content/')[1]||'')}catch{return ''}}).filter(Boolean);if(paths.length)await db.storage.from('content').remove(paths);await send(data?.length?'Contenu supprimé du site.':'Aucun contenu correspondant.',msg.chat.id);return reply('OK')}
if(isPrivate)return reply('Envoyez les publications dans la chaîne');
const text=msg.caption||msg.text||'';const tags=[...new Set([...text.matchAll(/#([\p{L}\p{N}_-]+)/gu)].map(m=>m[1].toLowerCase()))];const media=msg.document||msg.video||msg.audio||msg.voice||msg.animation||msg.photo?.at(-1);let type:'pdf'|'image'|'video'|'audio'|'text'|'other'='text';if(msg.photo)type='image';else if(msg.video||msg.animation)type='video';else if(msg.audio||msg.voice)type='audio';else if(msg.document)type=media?.mime_type==='application/pdf'||media?.file_name?.toLowerCase().endsWith('.pdf')?'pdf':media?.mime_type?.startsWith('image/')?'image':media?.mime_type?.startsWith('video/')?'video':media?.mime_type?.startsWith('audio/')?'audio':'other';
const {data:existing,error:lookupError}=await db.from('posts').select('*').eq('telegram_chat_id',msg.chat.id).eq('telegram_message_id',msg.message_id).maybeSingle();if(lookupError)throw lookupError;
const fetchMedia=async(fileId:string,mime:string)=>{const result=await fetch(`https://api.telegram.org/bot${token}/getFile?file_id=${encodeURIComponent(fileId)}`);const data=await result.json();if(!result.ok||!data.ok||!data.result.file_path)throw new Error('getFile impossible (fichier trop volumineux ?)');const path=String(data.result.file_path);const response=await fetch(`https://api.telegram.org/file/bot${token}/${path}`);if(!response.ok)throw new Error('Téléchargement Telegram impossible');const bytes=await response.arrayBuffer();const ext=path.split('.').at(-1)?.replace(/[^a-z0-9]/gi,'')||'bin';const object=`${msg.chat.id}/${msg.message_id}/${crypto.randomUUID()}.${ext}`;const {error}=await db.storage.from('content').upload(object,bytes,{contentType:mime,upsert:false});if(error)throw error;return db.storage.from('content').getPublicUrl(object).data.publicUrl};
let fileUrl=existing?.file_url||null;let thumbnailUrl=existing?.thumbnail_url||null;if(media){fileUrl=await fetchMedia(media.file_id,media.mime_type||'application/octet-stream');if(media.thumbnail){try{thumbnailUrl=await fetchMedia(media.thumbnail.file_id,'image/jpeg')}catch(e){console.error('Thumbnail:',e)}}else if(type==='image')thumbnailUrl=fileUrl}else{fileUrl=null;thumbnailUrl=null}
const title=(text.split('\n')[0].replace(/#[\p{L}\p{N}_-]+/gu,'').trim()||media?.file_name||'Nouvelle ressource').slice(0,160);const values={telegram_chat_id:msg.chat.id,telegram_message_id:msg.message_id,title,description:text,type,file_url:fileUrl,thumbnail_url:thumbnailUrl,file_size:media?.file_size||null,mime_type:media?.mime_type||null,category:tags[0]||'Général',tags,created_at:new Date((msg as Msg & {date?:number}).date?((msg as Msg & {date:number}).date)*1000:Date.now()).toISOString()};const {error}=await db.from('posts').upsert(values,{onConflict:'telegram_chat_id,telegram_message_id'});if(error)throw error;if(existing){const oldUrls=[existing.file_url,existing.thumbnail_url].filter((url:string|null)=>url&&url!==fileUrl&&url!==thumbnailUrl);const paths=oldUrls.map((url:string)=>{try{return decodeURIComponent(new URL(url).pathname.split('/storage/v1/object/public/content/')[1]||'')}catch{return ''}}).filter(Boolean);if(paths.length)await db.storage.from('content').remove(paths)}return reply('OK')}catch(error){console.error(error);return reply('Erreur temporaire',500)}});
